const colors = {
  inactiveIconBottomTab: '#8e8e8f',
  COLOR_GREEN: '#007a3d',
  COLOR_RED: '#da251c',
  COLOR_WHITE: '#FFFFFF',
  COLOR_BLACK: '#000000',
  COLOR_PLACEHOLDER: '#888888',
  COLOR_WHITE_GREY: '#eeeeee',
  COLOR_GREY: 'grey',

  //---native-base-----
  COLOR_NATIVE_BASE_SUCCESS_700: '#15803d',
  COLOR_NATIVE_BASE_LIGHT_300: '#d6d3d1',

  ///---------
  COLOR_PRIMARY: '#2ec7ab',
  COLOR_SECONDARY: '#111',
  COLOR_GREY_WHITE: '#fafafa',
  COLOR_DARK_SEPERATOR: '#d4d4d4',
  COLOR_BLACK_TRANSP: 'rgba(0, 0, 0, 0.7)',
  COLOR_GREY_TRANSP: 'rgba(67, 85, 85, 0.7)',
  COLOR_BLUE: '#5A8ED1',
  COLOR_RED_ORANGE: '#FF655B',
  COLOR_PINK: '#F178B6',
  COLOR_DARK_BLUE: '#1A2246',
  COLOR_UNDERLAY_BLUE: '#2466BA',
  COLOR_UNDERLAY_BUTTON_BACK: '#47A2DF',
  COLOR_UNDERLAY_BUTTON_PINK: '#E41D83',
  COLOR_UNDERLAY_BUTTON_RED: '#D22E24',
  COLOR_UNDERLAY_BUTTON_WHITE: '#D8D8D8',
  COLOR_UNDERLAY_BUTTON_BLACK: '#dcdcdc',
  COLOR_ERROR: '#FF655B',
  COLOR_DISABLE: '#AAAAAA',
  COLOR_LOADING_PLACEHOLDER: '#bdbdbd',
  COLOR_LOCATION_LOCK: '#D1731D',

  //chart
  COLOR_CHART_BLUE: '#2CE3DD',
  COLOR_CHART_RED: '#E9222A',
  COLOR_AREA_CHART_BLUE: '#2C59D6',
  COLOR_AREA_CHART_GREEN_BOW: '#22E9E1',
  COLOR_AREA_CHART_GREEN: '#22E96A',
  COLOR_AREA_CHART_RED: '#E9222A',
};

export default colors;
