# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assemble", build_type: 'Release')
    firebase_app_distribution(
      app: "1:1026480421038:android:df8574ca732170a32ad53f",
      testers: "datd2537@gmail.com",
      firebase_cli_token: "1//0e2XHuL37lGJ5CgYIARAAGA4SNwF-L9IrApgVmvnVfl5yi-WRzS7dexiqVRVtRo0d85j6OgjdkgS8SQBgu2GbV0STNSaPLCohkF4",
      release_notes: "
        - phiên bản đầu tiên
        "
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
